name: email_newsletter
services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=app
      - POSTGRES_DB=newsletter